garums = input("Garums?")
platums = input("Platums?")
augstums = input("Augstums?")
garums = float(garums)
platums = float(platums)
augstums = float(augstums)
print(f"Telpas izmērs ir {garums*platums*augstums} m3")